	soc_system u0 (
		.avalon_bridge_external_interface_address     (<connected-to-avalon_bridge_external_interface_address>),     //    avalon_bridge_external_interface.address
		.avalon_bridge_external_interface_byte_enable (<connected-to-avalon_bridge_external_interface_byte_enable>), //                                    .byte_enable
		.avalon_bridge_external_interface_read        (<connected-to-avalon_bridge_external_interface_read>),        //                                    .read
		.avalon_bridge_external_interface_write       (<connected-to-avalon_bridge_external_interface_write>),       //                                    .write
		.avalon_bridge_external_interface_write_data  (<connected-to-avalon_bridge_external_interface_write_data>),  //                                    .write_data
		.avalon_bridge_external_interface_acknowledge (<connected-to-avalon_bridge_external_interface_acknowledge>), //                                    .acknowledge
		.avalon_bridge_external_interface_read_data   (<connected-to-avalon_bridge_external_interface_read_data>),   //                                    .read_data
		.audio_subsystem_audio_ADCDAT                 (<connected-to-audio_subsystem_audio_ADCDAT>),                 //               audio_subsystem_audio.ADCDAT
		.audio_subsystem_audio_ADCLRCK                (<connected-to-audio_subsystem_audio_ADCLRCK>),                //                                    .ADCLRCK
		.audio_subsystem_audio_BCLK                   (<connected-to-audio_subsystem_audio_BCLK>),                   //                                    .BCLK
		.audio_subsystem_audio_DACDAT                 (<connected-to-audio_subsystem_audio_DACDAT>),                 //                                    .DACDAT
		.audio_subsystem_audio_DACLRCK                (<connected-to-audio_subsystem_audio_DACLRCK>),                //                                    .DACLRCK
		.audio_subsystem_audio_pll_clk_clk            (<connected-to-audio_subsystem_audio_pll_clk_clk>),            //       audio_subsystem_audio_pll_clk.clk
		.audio_subsystem_audio_pll_ref_clk_clk        (<connected-to-audio_subsystem_audio_pll_ref_clk_clk>),        //   audio_subsystem_audio_pll_ref_clk.clk
		.audio_subsystem_audio_pll_ref_reset_reset    (<connected-to-audio_subsystem_audio_pll_ref_reset_reset>),    // audio_subsystem_audio_pll_ref_reset.reset
		.av_config_external_interface_SDAT            (<connected-to-av_config_external_interface_SDAT>),            //        av_config_external_interface.SDAT
		.av_config_external_interface_SCLK            (<connected-to-av_config_external_interface_SCLK>),            //                                    .SCLK
		.hex3_hex0_external_connection_export         (<connected-to-hex3_hex0_external_connection_export>),         //       hex3_hex0_external_connection.export
		.hex5_hex4_external_connection_export         (<connected-to-hex5_hex4_external_connection_export>),         //       hex5_hex4_external_connection.export
		.hps_io_hps_io_emac1_inst_TX_CLK              (<connected-to-hps_io_hps_io_emac1_inst_TX_CLK>),              //                              hps_io.hps_io_emac1_inst_TX_CLK
		.hps_io_hps_io_emac1_inst_TXD0                (<connected-to-hps_io_hps_io_emac1_inst_TXD0>),                //                                    .hps_io_emac1_inst_TXD0
		.hps_io_hps_io_emac1_inst_TXD1                (<connected-to-hps_io_hps_io_emac1_inst_TXD1>),                //                                    .hps_io_emac1_inst_TXD1
		.hps_io_hps_io_emac1_inst_TXD2                (<connected-to-hps_io_hps_io_emac1_inst_TXD2>),                //                                    .hps_io_emac1_inst_TXD2
		.hps_io_hps_io_emac1_inst_TXD3                (<connected-to-hps_io_hps_io_emac1_inst_TXD3>),                //                                    .hps_io_emac1_inst_TXD3
		.hps_io_hps_io_emac1_inst_RXD0                (<connected-to-hps_io_hps_io_emac1_inst_RXD0>),                //                                    .hps_io_emac1_inst_RXD0
		.hps_io_hps_io_emac1_inst_MDIO                (<connected-to-hps_io_hps_io_emac1_inst_MDIO>),                //                                    .hps_io_emac1_inst_MDIO
		.hps_io_hps_io_emac1_inst_MDC                 (<connected-to-hps_io_hps_io_emac1_inst_MDC>),                 //                                    .hps_io_emac1_inst_MDC
		.hps_io_hps_io_emac1_inst_RX_CTL              (<connected-to-hps_io_hps_io_emac1_inst_RX_CTL>),              //                                    .hps_io_emac1_inst_RX_CTL
		.hps_io_hps_io_emac1_inst_TX_CTL              (<connected-to-hps_io_hps_io_emac1_inst_TX_CTL>),              //                                    .hps_io_emac1_inst_TX_CTL
		.hps_io_hps_io_emac1_inst_RX_CLK              (<connected-to-hps_io_hps_io_emac1_inst_RX_CLK>),              //                                    .hps_io_emac1_inst_RX_CLK
		.hps_io_hps_io_emac1_inst_RXD1                (<connected-to-hps_io_hps_io_emac1_inst_RXD1>),                //                                    .hps_io_emac1_inst_RXD1
		.hps_io_hps_io_emac1_inst_RXD2                (<connected-to-hps_io_hps_io_emac1_inst_RXD2>),                //                                    .hps_io_emac1_inst_RXD2
		.hps_io_hps_io_emac1_inst_RXD3                (<connected-to-hps_io_hps_io_emac1_inst_RXD3>),                //                                    .hps_io_emac1_inst_RXD3
		.hps_io_hps_io_qspi_inst_IO0                  (<connected-to-hps_io_hps_io_qspi_inst_IO0>),                  //                                    .hps_io_qspi_inst_IO0
		.hps_io_hps_io_qspi_inst_IO1                  (<connected-to-hps_io_hps_io_qspi_inst_IO1>),                  //                                    .hps_io_qspi_inst_IO1
		.hps_io_hps_io_qspi_inst_IO2                  (<connected-to-hps_io_hps_io_qspi_inst_IO2>),                  //                                    .hps_io_qspi_inst_IO2
		.hps_io_hps_io_qspi_inst_IO3                  (<connected-to-hps_io_hps_io_qspi_inst_IO3>),                  //                                    .hps_io_qspi_inst_IO3
		.hps_io_hps_io_qspi_inst_SS0                  (<connected-to-hps_io_hps_io_qspi_inst_SS0>),                  //                                    .hps_io_qspi_inst_SS0
		.hps_io_hps_io_qspi_inst_CLK                  (<connected-to-hps_io_hps_io_qspi_inst_CLK>),                  //                                    .hps_io_qspi_inst_CLK
		.hps_io_hps_io_sdio_inst_CMD                  (<connected-to-hps_io_hps_io_sdio_inst_CMD>),                  //                                    .hps_io_sdio_inst_CMD
		.hps_io_hps_io_sdio_inst_D0                   (<connected-to-hps_io_hps_io_sdio_inst_D0>),                   //                                    .hps_io_sdio_inst_D0
		.hps_io_hps_io_sdio_inst_D1                   (<connected-to-hps_io_hps_io_sdio_inst_D1>),                   //                                    .hps_io_sdio_inst_D1
		.hps_io_hps_io_sdio_inst_CLK                  (<connected-to-hps_io_hps_io_sdio_inst_CLK>),                  //                                    .hps_io_sdio_inst_CLK
		.hps_io_hps_io_sdio_inst_D2                   (<connected-to-hps_io_hps_io_sdio_inst_D2>),                   //                                    .hps_io_sdio_inst_D2
		.hps_io_hps_io_sdio_inst_D3                   (<connected-to-hps_io_hps_io_sdio_inst_D3>),                   //                                    .hps_io_sdio_inst_D3
		.hps_io_hps_io_usb1_inst_D0                   (<connected-to-hps_io_hps_io_usb1_inst_D0>),                   //                                    .hps_io_usb1_inst_D0
		.hps_io_hps_io_usb1_inst_D1                   (<connected-to-hps_io_hps_io_usb1_inst_D1>),                   //                                    .hps_io_usb1_inst_D1
		.hps_io_hps_io_usb1_inst_D2                   (<connected-to-hps_io_hps_io_usb1_inst_D2>),                   //                                    .hps_io_usb1_inst_D2
		.hps_io_hps_io_usb1_inst_D3                   (<connected-to-hps_io_hps_io_usb1_inst_D3>),                   //                                    .hps_io_usb1_inst_D3
		.hps_io_hps_io_usb1_inst_D4                   (<connected-to-hps_io_hps_io_usb1_inst_D4>),                   //                                    .hps_io_usb1_inst_D4
		.hps_io_hps_io_usb1_inst_D5                   (<connected-to-hps_io_hps_io_usb1_inst_D5>),                   //                                    .hps_io_usb1_inst_D5
		.hps_io_hps_io_usb1_inst_D6                   (<connected-to-hps_io_hps_io_usb1_inst_D6>),                   //                                    .hps_io_usb1_inst_D6
		.hps_io_hps_io_usb1_inst_D7                   (<connected-to-hps_io_hps_io_usb1_inst_D7>),                   //                                    .hps_io_usb1_inst_D7
		.hps_io_hps_io_usb1_inst_CLK                  (<connected-to-hps_io_hps_io_usb1_inst_CLK>),                  //                                    .hps_io_usb1_inst_CLK
		.hps_io_hps_io_usb1_inst_STP                  (<connected-to-hps_io_hps_io_usb1_inst_STP>),                  //                                    .hps_io_usb1_inst_STP
		.hps_io_hps_io_usb1_inst_DIR                  (<connected-to-hps_io_hps_io_usb1_inst_DIR>),                  //                                    .hps_io_usb1_inst_DIR
		.hps_io_hps_io_usb1_inst_NXT                  (<connected-to-hps_io_hps_io_usb1_inst_NXT>),                  //                                    .hps_io_usb1_inst_NXT
		.hps_io_hps_io_spim1_inst_CLK                 (<connected-to-hps_io_hps_io_spim1_inst_CLK>),                 //                                    .hps_io_spim1_inst_CLK
		.hps_io_hps_io_spim1_inst_MOSI                (<connected-to-hps_io_hps_io_spim1_inst_MOSI>),                //                                    .hps_io_spim1_inst_MOSI
		.hps_io_hps_io_spim1_inst_MISO                (<connected-to-hps_io_hps_io_spim1_inst_MISO>),                //                                    .hps_io_spim1_inst_MISO
		.hps_io_hps_io_spim1_inst_SS0                 (<connected-to-hps_io_hps_io_spim1_inst_SS0>),                 //                                    .hps_io_spim1_inst_SS0
		.hps_io_hps_io_uart0_inst_RX                  (<connected-to-hps_io_hps_io_uart0_inst_RX>),                  //                                    .hps_io_uart0_inst_RX
		.hps_io_hps_io_uart0_inst_TX                  (<connected-to-hps_io_hps_io_uart0_inst_TX>),                  //                                    .hps_io_uart0_inst_TX
		.hps_io_hps_io_i2c0_inst_SDA                  (<connected-to-hps_io_hps_io_i2c0_inst_SDA>),                  //                                    .hps_io_i2c0_inst_SDA
		.hps_io_hps_io_i2c0_inst_SCL                  (<connected-to-hps_io_hps_io_i2c0_inst_SCL>),                  //                                    .hps_io_i2c0_inst_SCL
		.hps_io_hps_io_i2c1_inst_SDA                  (<connected-to-hps_io_hps_io_i2c1_inst_SDA>),                  //                                    .hps_io_i2c1_inst_SDA
		.hps_io_hps_io_i2c1_inst_SCL                  (<connected-to-hps_io_hps_io_i2c1_inst_SCL>),                  //                                    .hps_io_i2c1_inst_SCL
		.key_external_connection_export               (<connected-to-key_external_connection_export>),               //             key_external_connection.export
		.ledr_external_connection_export              (<connected-to-ledr_external_connection_export>),              //            ledr_external_connection.export
		.memory_mem_a                                 (<connected-to-memory_mem_a>),                                 //                              memory.mem_a
		.memory_mem_ba                                (<connected-to-memory_mem_ba>),                                //                                    .mem_ba
		.memory_mem_ck                                (<connected-to-memory_mem_ck>),                                //                                    .mem_ck
		.memory_mem_ck_n                              (<connected-to-memory_mem_ck_n>),                              //                                    .mem_ck_n
		.memory_mem_cke                               (<connected-to-memory_mem_cke>),                               //                                    .mem_cke
		.memory_mem_cs_n                              (<connected-to-memory_mem_cs_n>),                              //                                    .mem_cs_n
		.memory_mem_ras_n                             (<connected-to-memory_mem_ras_n>),                             //                                    .mem_ras_n
		.memory_mem_cas_n                             (<connected-to-memory_mem_cas_n>),                             //                                    .mem_cas_n
		.memory_mem_we_n                              (<connected-to-memory_mem_we_n>),                              //                                    .mem_we_n
		.memory_mem_reset_n                           (<connected-to-memory_mem_reset_n>),                           //                                    .mem_reset_n
		.memory_mem_dq                                (<connected-to-memory_mem_dq>),                                //                                    .mem_dq
		.memory_mem_dqs                               (<connected-to-memory_mem_dqs>),                               //                                    .mem_dqs
		.memory_mem_dqs_n                             (<connected-to-memory_mem_dqs_n>),                             //                                    .mem_dqs_n
		.memory_mem_odt                               (<connected-to-memory_mem_odt>),                               //                                    .mem_odt
		.memory_mem_dm                                (<connected-to-memory_mem_dm>),                                //                                    .mem_dm
		.memory_oct_rzqin                             (<connected-to-memory_oct_rzqin>),                             //                                    .oct_rzqin
		.sw_1_external_connection_export              (<connected-to-sw_1_external_connection_export>),              //            sw_1_external_connection.export
		.system_pll_ref_clk_clk                       (<connected-to-system_pll_ref_clk_clk>),                       //                  system_pll_ref_clk.clk
		.system_pll_ref_reset_reset                   (<connected-to-system_pll_ref_reset_reset>),                   //                system_pll_ref_reset.reset
		.system_pll_sdram_clk_clk                     (<connected-to-system_pll_sdram_clk_clk>),                     //                system_pll_sdram_clk.clk
		.audio_input_external_connection_export       (<connected-to-audio_input_external_connection_export>),       //     audio_input_external_connection.export
		.audio_ctrl_external_connection_export        (<connected-to-audio_ctrl_external_connection_export>)         //      audio_ctrl_external_connection.export
	);

